version: '3.8'

services:
  db:
    build: .
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bigdata_energia
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
